server:
  port: 8761            # standard port used for Eureka Server

spring:
  application:
    name: eureka        # acts as ID for the eureka discovery client

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
