server:
  # Standard port used for Eureka Server.
  port: 8761

spring:
  application:
    # Acts as ID for the Eureka Discovery Client used by other microservices.
    name: eureka
  output:
    ansi:
      enabled: ALWAYS

# Prevent the Discovery Server from including itself in the service registry.
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false